### ISSUE TITLE
下载一段时间后， 会有很大的上传流量

### ISSUE THREAD

**Issue by aj3423** [monkeyWie/gopeed-extension-baiduwp#11]
系统装了全局流量监控， 下载视频刚开始没有监控到上传流量，30分钟后看，以4m/秒的速度在上传。用wireshark抓包看到目的地址是 ...pan..shifen.com， 看上去就是不停往百度网盘在发包。是个bug？

**Comment by monkeyWie** [comment]
有没有可能不是gopeed的上传流量吗

**Comment by aj3423** [comment]
机器没有开其他东西，只开了gopeed。把gopeed进程结束之后，上传流量瞬间就变0了。

现在在下载2个视频，基本没速度的情况下，wireshark抓了5秒钟包，如图：
![image](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/4710875/f9bc7047-e63d-4a1f-ac66-8e6a084c9ee3)
[wireshark抓包5秒.zip](https://github.com/monkeyWie/gopeed-extension-baiduwp/files/15024311/wireshark.5.zip)

**Comment by monkeyWie** [comment]
看了下这些域名在代码里都没有，你可以通过目标ip把对应的进程ID找出来看看，唯一可能出现的上传流量就是gopeed会一直刷新任务列表数据，如果你的任务比较多的话可能确实会存在这个问题，不过这只是本地回环的流量

**Comment by aj3423** [comment]
之前任务里有10多个，其他都下载完了，剩下2个下载到一半就再也不动了，现在任务里只剩下这2个视频，这时候我结束gopeed进程，再打开，开始下载这两个，速度还是一直是0。

此时抓https内容看到大量的这种403请求，每秒10来个
![image](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/4710875/21af4e34-dce1-4e7d-8e67-efcf074e64ec)

Request 的 Cookie有大量重复的BAIDUID， 而且越来越多，感觉这可能是跑一段时间后占用上传流量的原因：
![image](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/4710875/7e97eeff-24ac-4636-b1ac-9c322ad4010b)

Response都是这个错误：
![image](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/4710875/95ebf588-eae6-44a5-a4c4-8ee3416fdba1)

mitmproxy抓的包：
[baidu.mitm.zip](https://github.com/monkeyWie/gopeed-extension-baiduwp/files/15024948/baidu.mitm.zip)

**Comment by monkeyWie** [comment]
好的，我大概知道啥原因了，403的时候会每隔1s就进行重试这个是正常的，然后重试的时候请求头无限递增导致上传流量暴涨，这应该是个bug了，非常感谢你的细节反馈！

**Comment by monkeyWie** [comment]
related: https://github.com/GopeedLab/gopeed/issues/488

**Comment by aj3423** [comment]
还有个问题是，这10个视频是同时下载的，为什么其他8集都成功下载了，这两集下载到一半就再也下不动了？
碰到这种403下不动的，是放着让他重试，一段时间后会恢复， 还是必须删除任务重新下载？
![image](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/4710875/619fc598-ffd1-4d54-8eef-aa055ae445a8)

**Comment by monkeyWie** [comment]
扩展有做自动重试的，或者暂停下再继续

**Comment by aj3423** [comment]
了解，不过这两个是好久都没动了，我再看看

**Comment by monkeyWie** [comment]
fixed in v1.5.7
