### ISSUE TITLE
对百度网盘分享的包含中文和链接的过滤下载

### ISSUE THREAD

**Issue by nief12** [monkeyWie/gopeed-extension-baiduwp#17]
因为直接从主页获取，只能获取到第一层，不够准确，可以直接用分享链接，这样就够准确了，但直接分享会带有中文和链接，不能直接复制粘贴，不知道方不方便对其做一个过滤，不知道技术方面方不方便

**Comment by monkeyWie** [comment]
百度网盘主页你进入文件夹也可以的，只要复制浏览器上的地址就可以解析下载当前对应目录的文件
