### ISSUE TITLE
带提取码的无法下载了。速度0

### ISSUE THREAD

**Issue by AZ663** [monkeyWie/gopeed-extension-baiduwp#18]
2024-06-09 23:18:57 ERR [monkeyWie@gopeed-extension-baiduwp] call function failed: onError error="Error: 获取下载链接失败，errno=9019"

**Comment by WalkerJay666** [comment]
同样的问题。

**Comment by qjr87** [comment]
如何解决？

**Comment by forbreak** [comment]
解决了没？

**Comment by Atul-8** [comment]
蹲结果

**Comment by githubstudy123456** [comment]
被官方ban了应该

**Comment by monkeyWie** [comment]
分享链接问题已修复，请更新到最新版本，并且按照教程设置cookie。
