### ISSUE TITLE
百度网盘下载进度为0。

### ISSUE THREAD

**Issue by pzb568** [monkeyWie/gopeed-extension-baiduwp#19]
![Screenshot_2024-10-20-05-00-55-55_166528d073cfd7065ce82d80c3b7a75a](https://github.com/user-attachments/assets/e7e41110-6400-4637-8845-f06690ac4316)

**Comment by monkeyWie** [comment]
分享链接问题已修复，请更新到最新版本，并且按照教程设置cookie。
