### ISSUE TITLE
解析百度网盘，自己的文件没问题，但分享链接解析错误

### ISSUE THREAD

**Issue by NJYZ-96** [monkeyWie/gopeed-extension-baiduwp#21]
![截图_20241113020811](https://github.com/user-attachments/assets/ffe0ae03-5c46-4386-a777-4a76d10e201d)
会解析出来这么个东西

我测试了多个分享链接，都会这样

我的密钥都按照扩展说明填写了，自己网盘的文件解析下载没问题
![截图_20241113020907](https://github.com/user-attachments/assets/89eeedd7-7c80-41be-b448-92b62eb65db8)

**Comment by monkeyWie** [comment]
分享链接问题已修复
