### ISSUE TITLE
无法通过网盘分享链接下载

### ISSUE THREAD

**Issue by tchxyc** [monkeyWie/gopeed-extension-baiduwp#3]
解析不了链接

使用的分享链接是 https://pan.baidu.com/s/1WsmMhDHLyt6e2-oPNv7TvQ?pwd=gty8

![gopeed_ofnPj5zE5H](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/49787317/bfb2e1a2-2046-4196-8ec0-75e7c746bc30)

已设置 bduss
![gopeed_Vr96npLj77](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/49787317/97c9b1aa-915a-438b-83bc-12b7753e8ec5)

**Comment by GD2021** [comment]
我也是

**Comment by monkeyWie** [comment]
麻烦上传日志看看， 在gopeed安装目录/logs/extensions.log

**Comment by tchxyc** [comment]
应该不是这个原因，刚才用自己保存的文件的分享链接是可以下载的。
我再多测试几次吧。

**Comment by znlsl** [comment]
我试了下，貌似的确是只有自己SVIP账户分享的链接可以下载，其他分享文件就和楼主的问题一样，获取分享信息失败
