### ISSUE TITLE
baidu解析的问题和建议

### ISSUE THREAD

**Issue by falltree** [monkeyWie/gopeed-extension-baiduwp#4]
折腾尝试百度云下载，发现了一些问题。
1. 自己网盘的软件下载，解析成功了，但是默认是全部勾选的，没有其他勾选的功能，比如全选，全不选，反选等等。这个功能很重要，比如我的网盘warez目录下有几百个软件，默认全勾选，可我通常要下载的就是最近存入的一个或几个最新的软件，这样我要点几百下，把那些不准备下载的文件全部去掉，要是有几千个文件呢（真有这样的目录），难道要点几千下？
![20231217171901](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/38394738/320d70c3-9211-4849-8244-ab1bfd8c6a2a)
因此强烈建议增加多种勾选方案，并且默认是全部不勾选，要下哪个就勾选哪个

2.别人分享的网盘链接，无法成功解析，已经加了?pwd=xxxx，但只能解析出一个莫名其妙的的结果
举例https://pan.baidu.com/s/1DcusDVY4EbpOmhPkr9KJrw  提取码：ftfe，我加入的链接为https://pan.baidu.com/s/1DcusDVY4EbpOmhPkr9KJrw?pwd=ftfe
得到的解析结果是
![20231217172753](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/38394738/7d237598-9474-4ea0-a27d-da89b1e2c766)

3. 补充一个youtube，输入url可直接解析，但是只有一个360p的链接，其余720p，1080p的都没有可选项。
例子：https://www.youtube.com/watch?v=9zvnKOf3gf4

**Comment by monkeyWie** [comment]
1. 这个问题和扩展无关，属于下载器的优化问题，建议提到 gopeed 主库去
2. 分享链接解析不了的问题我看看能不能修复吧
3. youtube 有些视频如果要高清的，就会把视频和音频分开，后面会考虑出个选项来下载音视频分开的情况。

**Comment by falltree** [comment]
不折腾了，准备放弃。
因为刚才尝试在另一台机器上用，用的portable版。复制了现成的token和BDUSS过去，然后自己的网盘都无法解析了。我猜想是需要那台机也重新获取一遍本机的token，BDUSS这些？

还有，获取扩展就没考虑本地化上传扩展文件吗，非要每台机都联网到github来在线获取？如果不记得获取扩展的网址怎么办，又重新上网去搜这个扩展的网址？

实话说，目前这个版本，离成熟可用的程度差太多了，随便体验一下，就这么多问题，下载速度也没任何优势，如果折腾那么多，效果还是只能和百度云pc版一样，那我直接用百度云好了，起码还不用折腾。

**Comment by monkeyWie** [comment]
走好不送

**Comment by falltree** [comment]
还注意到一个问题，比如我的网盘的目录地址解析出来是 /warez下方的所有子目录和文件，我下载其中一个子目录win10下的一个iso文件。准备下载到E:\down这个目录下，
解析成功，开始下载后，软件就会自动在E:\down下生成一个win10的子目录，然后把下载的iso放到E:\down\win10下，这一点也令人困惑，因为我不是要它下载子目录，只需要里面其中一个文件。如果我需要下载到E:\down\win10，我就会手动指定下载目录为E:\down\win10，然而如果我设置了E:\down\win10，结果就会下载到E:\down\win10\win10下。

综合以上这些，都是软件可以变得更好用更人性化的地方。
当然，不少软件作者都不喜欢听这些“批评”的意见，觉得自己的软件足够好，你用不好是因为你不会用，容易把对软件的意见理解成对作者的攻击，对此，我也没什么好说的，就这样吧，我个人永远选择真话，因为真话或许难听，但是有用。
