### ISSUE TITLE
I can't install baiduwp

### ISSUE THREAD

**Issue by zyh778** [monkeyWie/gopeed-extension-baiduwp#5]
![image](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/96773592/ce34fb00-7b6a-4953-be5c-b37383000392)
How I solved the problem

**Comment by monkeyWie** [comment]
The network seems unstable, maybe you can set up a proxy or use a VPN to improve it.

**Comment by zyh778** [comment]
I have set up a proxy to install, but it still won't complete the installation.

**Comment by TracReggie** [comment]
I got the same problem.

**Comment by monkeyWie** [comment]
You can also use minor repository url to install, such as: https://mirror.ghproxy.com/https://github.com/monkeyWie/gopeed-extension-baiduwp

**Comment by zyh778** [comment]
Problem solved, thank you very much for your help
