### ISSUE TITLE
插件安装失败

### ISSUE THREAD

**Issue by lumia1998** [monkeyWie/gopeed-extension-baiduwp#6]
N3150的群晖7.2的docker部署
![image](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/63107956/793536b3-b3a9-446e-8648-4a60cc48fbc0)
anzha安装插件提示这个,任何插件都是
请问如何解决

**Comment by monkeyWie** [comment]
我这里测试是成功的，Gopeed版本v1.5.5

![image](https://github.com/monkeyWie/gopeed-extension-baiduwp/assets/13160176/27477b24-c271-4c88-9446-5684221e0378)

应该都是网络问题导致的，可以参考下这个issue: https://github.com/monkeyWie/gopeed-extension-baiduwp/issues/5
